version: 0.0
os: linux
files:
  - source: /
    destination: /core/
hooks:
   ApplicationStop:
     - location: /stop.sh
       timeout: 300
   ApplicationStart:
     - location: /run.sh
       timeout: 300